# 图形 {#advanced}


## raster

星号 * 标记的是 S3 方法

```{r}
methods(plot)
```

查看函数的定义

```{r}
getAnywhere(plot.raster)
```

rasterImage 函数来绘制图像，如果想知道 `rasterImage` 的内容可以继续看 `getAnywhere(rasterImage)`

```{r}
getAnywhere(rasterImage)
```

通过查看函数的帮助 `?rasterImage` ，我们需要重点关注一下
参数 *image* 传递的 raster 对象

## sp

空间数据对象，以类 sp 方式存储 [@Pebesma_2005_sp]

```{r,eval=FALSE}
library(sp)
data(meuse)
coords <- SpatialPoints(meuse[c("x", "y")])
meuse <- SpatialPointsDataFrame(coords, meuse)
plot(meuse, pch = 1, cex = .05 * sqrt(meuse$zinc))

library(maptools)
fname <- system.file("shapes/sids.shp", package = "maptools")
p4s <- CRS("+proj=longlat +datum=NAD27")
nc <- readShapePoly(fname, proj4string = p4s)
plot(nc, axes = TRUE, col = grey(1 - nc$SID79 / 57))

# Trellis maps

arrow <- list("SpatialPolygonsRescale",
  layout.north.arrow(2),
  offset = c(-76, 34), scale = 0.5, which = 2
)
spplot(nc, c("SID74", "SID79"),
  as.table = TRUE,
  scales = list(draw = T), sp.layout = arrow
)
```

::: warning
maptools 提供的 readShapePoly 函数去读取 shp 文件的方式已经过时，推荐使用 `rgdal::readOGR` 或者 `sf::st_read` 方式读取
:::

## sf {#simple-features}

- maps
- mapdata
- maptools
- mapproj

- rgeos
- rgdal

- sp
- sf

