# 动态图形 {#interactive-graphics}

这里的动态图形覆盖的范围是各种 JS 库，不包含 tcltk、 rgl 和 svg 里面的动图，当然也不包括由静态图形转化过来的图形如 animation 或者 magick 和 gganimate 制作的图形 

## plotly

各种动态图形

```{r,echo=TRUE}
library(ggplot2)
library(plotly, warn.conflicts = FALSE)
packageVersion("plotly")
set.seed(2)
values <- rnorm(50)
p1 <- plot_ly(x = values, type = "histogram", name = "default")
p2 <- plot_ly(y = values, type = "histogram", name = "flipped")
subplot(p1, p2)
```



## 网络图 {#network}

[visNetwork](https://github.com/datastorm-open/visNetwork) 基于 vis.js 库

```{r,echo=TRUE}
library(visNetwork)
nodes <- data.frame(id = 1:7, label = 1:7)
edges <- data.frame(
  from = c(1, 2, 2, 2, 3, 3, 2),
  to = c(2, 3, 4, 5, 6, 7, 7)
)
```

从上到下的方向

```{r,echo=TRUE}
visNetwork(nodes, edges, width = "100%") %>%
  visEdges(arrows = "from") %>%
  visHierarchicalLayout() # same as visLayout(hierarchical = TRUE)
```

从左到右的方向

```{r,echo=TRUE}
visNetwork(nodes, edges, width = "100%") %>%
  visEdges(arrows = "to") %>%
  visHierarchicalLayout(direction = "LR", levelSeparation = 500)
```

