# 交互式图形 {#interactive-graphics}

这里的动态图形覆盖的范围是各种 JS 库，不包含 tcltk、 rgl 和 svg 里面的动图，当然也不包括由静态图形转化过来的图形如 animation 或者 magick 和 gganimate 制作的图形 

## plotly

各种动态图形

```{r,echo=TRUE}
library(ggplot2)
library(plotly, warn.conflicts = FALSE)
packageVersion("plotly")
set.seed(2)
values <- rnorm(50)
p1 <- plot_ly(x = values, type = "histogram", name = "default")
p2 <- plot_ly(y = values, type = "histogram", name = "flipped")
subplot(p1, p2)
```

## highcharter 

美国失业率数据

```r
data(unemployment,package = "highcharter")
temp <-  unlist(strsplit(unemployment[,2],",")) # 拆成两列
unique(temp[seq(from=2,to = length(temp),by=2)]) # 51 个州
# US Counties unemployment rate
# code: The county code.
# 
# name: The county name.
# 
# value: The unemployment.
# A data.frame with 3 variables and 3216 observations.
```

```{r,echo=TRUE}
library(highcharter)
data(unemployment)
hcmap("countries/us/us-all-all", data = unemployment,
      name = "Unemployment", value = "value", joinBy = c("hc-key", "code"),
      borderColor = "transparent") %>%
  hc_colorAxis(dataClasses = color_classes(c(seq(0, 10, by = 2), 50))) %>% 
  hc_legend(layout = "vertical", align = "right",
            floating = TRUE, valueDecimals = 0, valueSuffix = "%")
```


## 网络图 {#network}

[visNetwork](https://github.com/datastorm-open/visNetwork) 基于 vis.js 库

```{r,echo=TRUE}
library(visNetwork)
nodes <- data.frame(id = 1:7, label = 1:7)
edges <- data.frame(
  from = c(1, 2, 2, 2, 3, 3, 2),
  to = c(2, 3, 4, 5, 6, 7, 7)
)
```

从上到下的方向

```{r,echo=TRUE}
visNetwork(nodes, edges, width = "100%") %>%
  visEdges(arrows = "from") %>%
  visHierarchicalLayout() # same as visLayout(hierarchical = TRUE)
```

从左到右的方向

```{r,echo=TRUE}
visNetwork(nodes, edges, width = "100%") %>%
  visEdges(arrows = "to") %>%
  visHierarchicalLayout(direction = "LR", levelSeparation = 500)
```

