# 面向对象编程 {#oo}

## 环境 {#environment-access}

environment(fun = NULL)
environment(fun) <- value

is.environment(x)

.GlobalEnv
globalenv()
.BaseNamespaceEnv

emptyenv()
baseenv()

new.env(hash = TRUE, parent = parent.frame(), size = 29L)

parent.env(env)
parent.env(env) <- value

environmentName(env)

env.profile(env)

## Return the Value of a Named Object

get(x, pos = -1, envir = as.environment(pos), mode = "any",
    inherits = TRUE)

mget(x, envir = as.environment(-1), mode = "any", ifnotfound,
     inherits = FALSE)

dynGet(x, ifnotfound = , minframe = 1L, inherits = FALSE)

get Return the Value of a Named Object

exists Is an Object Defined?

exists(x, where = -1, envir = , frame, mode = "any",
       inherits = TRUE)

get0(x, envir = pos.to.env(-1L), mode = "any", inherits = TRUE,
     ifnotfound = NULL)

##  calling stack.

Functions to Access the Function Call Stack

sys.call(which = 0)
sys.frame(which = 0)
sys.nframe()
sys.function(which = 0)
sys.parent(n = 1)

sys.calls()
sys.frames()
sys.parents()
sys.on.exit()
sys.status()
parent.frame(n = 1)

sys.source Parse and Evaluate Expressions from a File


## 闭包 {#closures}

An illustration of lexical scoping.

```r
demo(scoping)
```

## 递归 {#recursion}

Using recursion for adaptive integration

```r
demo(recursion)
```

## 异常捕获和处理 {#catching-and-handling-errors}


```r
demo(error.catching)
```

## 判断对象属性 {#is-things}

```r
demo(is.things)
```


## 除虫 {#debug}

[Debugging with RStudio](https://support.rstudio.com/hc/en-us/articles/205612627)
